services:
  python-app:
    build: .
    container_name: python-app
    working_dir: /app

    volumes:
      - .:/app
    
    user: "${UID:-1000}:${GID:-1000}"

    environment:
      - PATH=/app/.venv/bin:$PATH
      - PROXY_HEADERS=true
      - FORWARDED_ALLOW_IPS=*
      - WS_PING_INTERVAL=20
      - WS_PING_TIMEOUT=20
      - UVICORN_WORKERS=1
      - THREAD_POOL_WORKERS=16
    
    ports:
      - "8000:8000"

    restart: unless-stopped
    
