services:
  python-app:
    build: .
    container_name: python-app
    working_dir: /app

    volumes:
      - .:/app
    
    environment:
      - PATH=/app/.venv/bin:$PATH
    
    ports:
      - "8000:8000"
    